### ISSUE TITLE
Initial Setup

### ISSUE THREAD

**Issue by jocelynshen** [footprnt/footprnt#1]
- Create 3 fragment pages and bottom nav bar
- Connect with Google maps API
- Set up parse server
- Create login and signup
- Create modal popup when long click on map

**Comment by jocelynshen** [comment]
finished last week

**Comment by stanleynwakamma** [comment]
Creating an account on the signup page leads back to the login page, can you please make it go to the Home page (map fragment) ?
And can create a toast that shows that an account already exists when a current user tries to signup again?
